name: Staffmode
version: '${project.version}'
main: com.brandan.staffmode.Main
api-version: 1.20
commands:
  unban:
    description: Unban a player
    permission: staffmode.unban
  ban:
    description: Ban a player
    permission: staffmode.ban
  tempban:
    description: Temporarily ban a player
    permission: staffmode.tempban
  vanish:
    description: Vanish a player
    permission: staffmode.vanish
    aliases:
      - v